name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: List contents of _site
        run: |
          echo "Listing contents of _site directory"
          pwd
          ls -l
          ls -la _site
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: ./_site

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: site
          path: ./_site
      - name: List contents of _site
        run: |
              echo "Listing contents of _site directory"
              pwd
              ls -l
              ls -la _site
          
      - name: Copy built site to gh-pages
        run: |
          pwd
          ls -l
          rm -rf ./*
          ls -l
          cp -r ./_site/* .

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Deploy Jekyll site via GitHub Actions'
          git push origin gh-pages
